### ISSUE TITLE
Logo at the homepage

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#135]
Please delete the university logo in the middle of the home page and reduce the space above and below it

**Comment by ahmedelbougha** [comment]
@LamiaSalah 
Where is that?

**Comment by HeshamHassan** [comment]
This logo:
![image](https://user-images.githubusercontent.com/11155105/39128354-3ddb7350-4710-11e8-9a73-650acc829af1.png)

**Comment by HeshamHassan** [comment]
As per Mr. Moustafa Instructions, kindly inform us about the settlement date of this issue.

**Comment by mahmoud-hussien1** [comment]
@LamiaSalah what about this space?
![screenshot from 2018-04-23 17 11 58](https://user-images.githubusercontent.com/35919348/39135656-b8eddd18-4719-11e8-8714-cad7da9a0746.png)
instead of this
![screenshot from 2018-04-23 17 12 18](https://user-images.githubusercontent.com/35919348/39135696-d2d9ad38-4719-11e8-8dbc-8f4e0cfe631f.png)

**Comment by ahmedelbougha** [comment]
@mahmoud-hussien1 
Please go ahead

**Comment by ahmedelbougha** [comment]
merged
