### ISSUE TITLE
Learning Paths Pages

### ISSUE THREAD

**Issue by LamiaSalah** [camelcasetechsd/skillsbuilder#166]
Please provide the option of adding text under the main titles for each learning paths

**Comment by mahmoud-hussien1** [comment]
@ahmedelbougha please advise.

**Comment by LamiaSalah** [comment]
@ahmedelbougha please advise the status

**Comment by ahmedelbougha** [comment]
Sunday 15/07/2018

**Comment by ahmedelbougha** [comment]
done

**Comment by LamiaSalah** [comment]
It's applied but the text is extremely aligned to the left, quite to the edge of the screen and it's not clear as in the attached
![capture](https://user-images.githubusercontent.com/37042927/42746433-0cbc8aac-88d8-11e8-85f6-2dcea293c11d.PNG)

**Comment by mahmoud-hussien1** [comment]
PR - https://bitbucket.org/camelcasetech/skillsbuilderpro/pull-requests/46/issue-166-make-text-under-learning-path/diff

**Comment by ahmedelbougha** [comment]
merged
@LamiaSalah 
please check and confirm.

**Comment by LamiaSalah** [comment]
@ahmedelbougha why there's a dot at the beginning of the second line in all paths?

**Comment by ahmedelbougha** [comment]
@LamiaSalah Because you are selecting the text direction to right to left from admin.
I changed `Personal Skills Builder`
![cat-r](https://user-images.githubusercontent.com/8982139/42845972-d552593e-8a17-11e8-8850-0bf97b7e090e.png)

While `Workplace Skills Builder` is still as is
![cat-w](https://user-images.githubusercontent.com/8982139/42846011-ea91f14c-8a17-11e8-98c2-6063a631baf9.png)

**Comment by LamiaSalah** [comment]
@ahmedelbougha Thanks
Confirmed
